### ISSUE TITLE
open names files as utf-8

### ISSUE THREAD

**Issue by soypunk** [Golan2072/CLGen#1]
https://github.com/Golan2072/CLGen/blob/802d5d620ca74c823d54723e59a197138260f7cb/stellagama.py#L85

This line should probably be:

`with open(filename, "r", encoding='utf-8', errors='ignore') as line_list:`

Because the various names files have non-ascii characters in them and seem to be utf-8 encoded.

**Comment by Golan2072** [comment]
Many thanks!

**Comment by Golan2072** [comment]
Resolved in new commit.
